statsd3/config/routes.rb
Statsd3::Application.routes.draw do

  resources :users do 
    resources :pages, except: [:index] do
      resources :page_stats, only: [:index]
      resources :page_metrics, only: [:index]
    end
  end

  resources :users_pages, only: [:index]
  resources :metric_variables

  root 'users#index'
end

statsd3/app/models/metric_variable.rb
class MetricVariable < ActiveRecord::Base

  METRIC_FLAGS = [['gauges','g'], ['counters','c'], ['timers','ms'], ['sets','s']]

  def self.find_metric_flag_key_by_value(value)
    METRIC_FLAGS.find { |k, v| v == value }.first
  end

end

statsd3/app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true
  
end

statsd3/app/models/user.rb
class User < ActiveRecord::Base
  has_many :pages, dependent: :destroy
end

statsd3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

statsd3/app/controllers/metric_variables_controller.rb
class MetricVariablesController < ApplicationController
  before_action :set_metric_variable, only: [:show, :edit, :update, :destroy]

  respond_to :json, :html

  def index
    @metric_variables = MetricVariable.all
    respond_with @metric_variables
  end

  def show
  end

  def new
    @metric_variable = MetricVariable.new
  end

  def edit
  end

  def create    
    @metric_variable = MetricVariable.new(metric_variable_params)
    flash[:notice] = 'Metric variable was successfully created.' if @metric_variable.save
    respond_with @metric_variable
  end

  def update
    if @metric_variable.update(metric_variable_params)
      flash[:notice] = 'Metric variable was successfully updated.'
    end
    respond_with @metric_variable
  end

  def destroy
    if @metric_variable.destroy
      flash[:notice] = 'Metric variable was successfully destroyed.'
    end
    respond_with @metric_variable
  end

  private

    def set_metric_variable
      @metric_variable = MetricVariable.find(params[:id])
    end

    def metric_variable_params
      params.require(:metric_variable).permit(:name, :metric_abr, :sample_rate)
    end
end

statsd3/app/controllers/page_metrics_controller.rb
class PageMetricsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @page = Page.find(params[:page_id])
    @metrics = MetricVariable.all
    
    @stats_path = user_page_page_stats_path(@user, @page)
    @metric_flag = params[:flag]
    @metric_var  = params[:metric]
  end

end

statsd3/app/controllers/page_stats_controller.rb
class PageStatsController < ApplicationController

  respond_to :json, :html

  def index    
    @user = User.find(params[:user_id])
    @page = Page.find(params[:page_id])
    require 'mongo_database'
    require 'page_stats'
    require 'page_metric_fetcher'

    pmf_args = { document: @user.api_key, page_id: @page.id }
    page_metric_fetcher = PageMetricFetcher.new(pmf_args)
    flag = params[:flag]
    metric_var = params[:metric_var]
    render json: page_metric_fetcher.fetch_metric(flag, metric_var)
  end

  def show

  end

end

statsd3/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_user
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def show
  end

  def new
    @page = @user.pages.new
  end

  def edit
  end

  def create
    @page = @user.pages.new(page_params)    
    flash[:notice] = 'Page was successfully created.' if @page.save
    respond_with @user, @page
  end

  def update
    flash[:notice] = 'Page was successfully updated.' if @page.update(page_params)
    respond_with @user, @page
  end

  def destroy
    flash[:notice] = 'Page was successfully destroyed.' if @page.destroy
    respond_with @user
  end

  private
    
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_page
      @page = @user.pages.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :slug, :body, :user_id)
    end
end

statsd3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  def index
    @users = User.all
    respond_with @users
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    flash[:notice] = 'User was successfully created.' if @user.save
    respond_with @user
  end

  def update
    flash[:notice] = 'User was successfully updated.' if @user.update(user_params)
    respond_with @user
  end

  def destroy    
    flash[:notice] = 'User was successfully destroyed.' if @user.destroy
    respond_with @user
  end

  private
    
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :api_key)
    end
end

statsd3/app/controllers/users_pages_controller.rb
class UsersPagesController < ApplicationController

  def index
    user_pages = User.all.map do |u|
     { id: u.id, api_key: u.api_key, pages: u.pages.select([:id, :title]) }
    end
    render json: user_pages.to_json
  end

end

statsd3/app/helpers/application_helper.rb
module ApplicationHelper

  ALERT_TYPES = [:error, :info, :success, :warning]
 
  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
       
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)
 
      Array(message).each do |msg|
        text = content_tag(:div,
          content_tag(:button, raw("×"), :class => "close", "data-dismiss" => "alert") +
          msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
    
end

statsd3/app/helpers/metric_variables_helper.rb
module MetricVariablesHelper
end

statsd3/app/helpers/page_metrics_helper.rb
module PageMetricsHelper

  def default_to_first_metric(flag, metric)
    if @metric_flag.nil? || @metric_flag.empty?
      @metric_flag = flag
      @metric_var  = metric
    end
  end

  def generate_tabs
    content_tag(:ul, class: 'nav nav-tabs', id: 'metric_tabs') do
      @metrics.each_with_index do |metric, idx|        
        default_to_first_metric(metric.metric_abr, metric.name) if idx == 0
        css_class = 'active' if @metric_var == metric.name

        concat content_tag(:li, 
          content_tag(:a, metric.name,
            href: "?flag=#{metric.metric_abr}&metric=#{metric.name}",
          ),
          class: css_class     
        )
      end
    end
  end

end

statsd3/app/helpers/pages_helper.rb
module PagesHelper
  
  def page_stat_path(stat)
    user_page_page_stats_path(@user, @page, stat: stat)
  end

end

statsd3/app/helpers/users_helper.rb
module UsersHelper
end

statsd3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Statsd3" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Statsd3", root_url, class: 'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Users", root_url, class: 'active' %></li>
            <li><%= link_to "Metric Variables", metric_variables_url %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

statsd3/app/views/metric_variables/_form.html.erb
<%= form_for [@metric_variable] do |f| %>

  <div class="well">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control", placeholder: "Enter a Metric Variable" %>
    </div>

    <div class="form-group">
      <%= f.label :metric_abr, "Metric Type" %>
      <%= f.select :metric_abr, MetricVariable::METRIC_FLAGS, {}, :class => "form-control" %>
    </div>

     <div class="form-group">
      <%= f.label :sample_rate, "Sample Rate" %>
      <%= f.text_field :sample_rate, :class => "form-control", placeholder: "Enter a Sample Rate", default: 1 %>
      <span class="help-block">Defaults to 1</span>
    </div>

  </div>

  <div class="btn-group btn-group-sm">
    <%= link_to "Back", metric_variables_url, class: "btn btn-default" %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

statsd3/app/views/metric_variables/edit.html.erb
<h3>Edit Metric Variable</h3>
<%= render 'form' %>

statsd3/app/views/metric_variables/index.html.erb
<h3>Listing Metrics</h3>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Flag</th>
      <th>Sample Rate</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <tfoot>
        <tr>
          <td colspan="4">
            <%= link_to 'New Metric', new_metric_variable_path, class: 'btn btn-primary' %>
          </td>
        </tr>
      </tfoot>
    <% @metric_variables.each do |metric_variable| %>
      <tr>
        <td><%= metric_variable.name %></td>
        <td><%= metric_variable.metric_abr %></td>
        <td><%= metric_variable.sample_rate %></td>
        <td>
          <div class="btn-group btn-group-sm pull-right">
            <%= link_to 'Show', metric_variable, class: 'btn btn-default' %>
            <%= link_to 'Edit', edit_metric_variable_path(metric_variable), class: 'btn btn-default' %>
            <%= link_to 'Destroy', metric_variable, 
              method: :delete, data: { confirm: 'Are you sure?' },
              class: 'btn btn-danger'
            %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

statsd3/app/views/metric_variables/new.html.erb
<h3>Create Metric Variable</h3>
<%= render 'form' %>

statsd3/app/views/metric_variables/show.html.erb
<h3>Listing Metric</h3>

<div class="list-group">
  <li class="list-group-item"><strong>Metric:</strong> <%= @metric_variable.name %></li>
  <li class="list-group-item"><strong>Flag:</strong> <%= @metric_variable.metric_abr %></li>
  <li class="list-group-item"><strong>Sample Rate:</strong> <%= @metric_variable.sample_rate %></li>
</div>

<div class="btn-group btn-group-sm">
  <%= link_to 'Back', metric_variables_path, class: 'btn btn-default' %>
  <%= link_to 'Edit', edit_metric_variable_path(@metric_variable), class: 'btn btn-default' %>  
  <%= link_to 'Destroy', @metric_variable, 
    method: :delete, data: { confirm: 'Are you sure?' },
    class: 'btn btn-danger'
  %>
</div>

statsd3/app/views/page_metrics/_d3_graph.html.erb
<% content_for :page_javascript do %>
  <script>
    // Supplied via page_stats_controller
    var json_url = "<%= @stats_path %>?flag=<%= @metric_flag%>&metric_var=<%= @metric_var %>";

    var margin = {top: 20, right: 20, bottom: 30, left: 50},
        width = 2400 - margin.left - margin.right,
        height = 300 - margin.top - margin.bottom;

    var parseDate = d3.time.format("%d-%b-%y").parse;

    var x = d3.time.scale()
        .range([0, width/4]);

    var y = d3.scale.linear()
        .range([height, 0]);

    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom");

    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left");

    var area = d3.svg.area()
        .x(function(d) { return x(d.time); })
        .y0(height)
        .y1(function(d) { return y(d.value); });

    var svg = d3.select("#d3graph").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
      .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    d3.json(json_url, function(error, data) {
      data.forEach(function(d) {
        m = new Date(d.time)
        d.time = new Date(d.time).getTime();
        d.value = +d.value;
      });

      x.domain(d3.extent(data, function(d) { return d.time; }));
      y.domain([0, 100]);

      svg.append("path")
          .datum(data)
          .attr("class", "area")
          .attr("d", area);

      svg.append("g")
          .attr("class", "x axis")
          .attr("transform", "translate(0," + height + ")")
          .call(xAxis);

      svg.append("g")
          .attr("class", "y axis")
          .call(yAxis)
        .append("text")
          .attr("transform", "rotate(-90)")
          .attr("y", 6)
          .attr("dy", ".71em")
          .style("text-anchor", "end")
          .text("<%= @metric_flag%> Flag")

    });

  </script>

<% end %>

statsd3/app/views/page_metrics/_d3_stylesheet.html.erb
<% content_for :page_stylesheet do %>
  <style>

    svg {
      font: 10px sans-serif;
    }

    .axis path,
    .axis line {
      fill: none;
      stroke: #000;
      shape-rendering: crispEdges;
    }

    .area {
      fill: steelblue;
    }

  </style>
<% end %>

statsd3/app/views/page_metrics/index.html.erb
<% render partial: 'd3_stylesheet' %>
<script src="http://d3js.org/d3.v3.js"></script>

<h3>Listing Page Metrics <small>: <%= @page.title %></small></h3>
<!-- page_metrics_helper -->
<%= generate_tabs %>

<div id="d3graph">
  <% render partial: 'd3_graph' %>
</div>

statsd3/app/views/pages/_form.html.erb
<%= form_for [@user, @page] do |f| %>

  <div class="well">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control", placeholder: "Enter a Page Title" %>
    </div>

    <div class="form-group">
      <%= f.label :slug, "API Key" %>
      <%= f.text_field :slug, :class => "form-control", placeholder: "Enter a Page Slug" %>
    </div>

    <div class="form-group">
      <%= f.label :body, "Body" %><br />
      <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Enter Page Body" %>
    </div>

  </div>

  <div class="btn-group btn-group-sm">
    <%= link_to "Back", @user, class: "btn btn-default" %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

statsd3/app/views/pages/_graph.html.erb
<strong>variable</strong>: <%= stat %>
<script>
  var margin = {top: 20, right: 20, bottom: 30, left: 50},
      width = 860 - margin.left - margin.right,
      height = 200 - margin.top - margin.bottom;

  var parseDate = d3.time.format("%d-%b-%y").parse;

  var x = d3.time.scale()
      .range([0, width]);

  var y = d3.scale.linear()
      .range([height, 0]);

  var xAxis = d3.svg.axis()
      .scale(x)
      .orient("bottom");

  var yAxis = d3.svg.axis()
      .scale(y)
      .orient("left");

  var line = d3.svg.line()
      .x(function(d) { return x(d.time); })
      .y(function(d) { return y(d.value); });

  var svg = d3.select("body").append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  d3.json("<%= page_stat_path(stat) %>", function(error, data) {
    data.forEach(function(d) {
      d.time = new Date(d.time);
      d.value = +d.value;
    });

    x.domain(d3.extent(data, function(d) { return d.time; }));
    y.domain(d3.extent(data, function(d) { return d.value; }));

    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)
      .append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", ".71em")
        .style("text-anchor", "end")
        .text("Count ($)");

    svg.append("path")
        .datum(data)
        .attr("class", "line")
        .attr("d", line);
  });
</script>

statsd3/app/views/pages/edit.html.erb
<h3>Edit User Page</h3>
<%= render :partial => 'form' %>

statsd3/app/views/pages/index.html.erb
Not Implemented

statsd3/app/views/pages/new.html.erb
<h3>Create User Page</h3>
<%= render :partial => 'form' %>

statsd3/app/views/pages/show.html.erb
<h3>Listing User Page</h3>

<div class="list-group">
  <li class="list-group-item"><strong>Title:</strong> <%= @page.title %></li>
  <li class="list-group-item"><strong>Slug:</strong> <%= @page.slug %></li>
  <li class="list-group-item"><strong>Body:</strong>
    <pre><code><%= @page.body %></code></pre>
  </li>
</div>

<div class="btn-group btn-group-sm">
  <%= link_to 'Back', user_path(@user), class: 'btn btn-default' %>
  <%= link_to 'Edit', edit_user_page_path(@user, @page), class: 'btn btn-default' %>  
  <%= link_to 'Destroy', user_page_path(@user, @page), 
    method: :delete, data: { confirm: 'Are you sure?' },
    class: 'btn btn-danger'
  %>
</div>

statsd3/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="well">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'form-control', placeholder: 'Enter a User Name' %>
    </div>

    <div class="form-group">
      <%= f.label :api_key, 'API Key' %>
      <%= f.text_field :api_key, :class => 'form-control', placeholder: 'Enter an API Key' %>
    </div>

  </div>

  <div class="btn-group btn-group-sm">
    <%= link_to 'Back', users_url, class: 'btn btn-default' %>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>

<% end %>

statsd3/app/views/users/edit.html.erb
<h3>Edit User</h3>
<%= render 'form' %>

statsd3/app/views/users/index.html.erb
<h3>Listing Users</h3>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Api Key</th>
      <th>Pages</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <tfoot>
        <tr>
          <td colspan="4">
            <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
          </td>
        </tr>
      </tfoot>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.api_key %></td>
        <td><%= user.pages.size %></td>
        <td>
          <div class="btn-group btn-group-sm pull-right">
            <%= link_to 'Show', user, class: 'btn btn-default' %>
            <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-default' %>
            <%= link_to 'Destroy', user, 
              method: :delete, data: { confirm: 'Are you sure?' },
              class: 'btn btn-danger'
            %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

statsd3/app/views/users/new.html.erb
<h3>Create User</h3>
<%= render 'form' %>

statsd3/app/views/users/show.html.erb
<h3>Listing User</h3>

<div class="list-group">
  <li class="list-group-item"><strong>Name:</strong> <%= @user.name %></li>
  <li class="list-group-item"><strong>API Key:</strong> <%= @user.api_key %></li>
  <li class="list-group-item"><strong>Current Pages</strong>
    <small>(<%= @user.pages.size %>)</small>
    <ul class="list-unstyled">
      <% @user.pages.each do |page| %>
        <li>
          <%= link_to page.title, user_page_path(@user, page) %>
          <small>( <%= link_to 'Metrics', user_page_page_metrics_path(@user, page) %> )</small>
        </li>
      <% end %>
    </ul>
    <%= link_to 'New Page', new_user_page_path(@user), class: 'btn btn-primary btn-xs' %>
  </li>
</div>

<div class="btn-group btn-group-sm">
  <%= link_to 'Back', users_path, class: 'btn btn-default' %>
  <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default' %>  
  <%= link_to 'Destroy', @user, 
    method: :delete, data: { confirm: 'Are you sure?' },
    class: 'btn btn-danger'
  %>
</div>